name: advpy
channels:
  - conda-forge
  - conda
dependencies:
  - python=3.7
  - numpy=1.18
  - pip
  - pandas=1.0.1
  - scipy=1.4.1
  - graphviz
  - python-graphviz
  - bokeh
  - xarray 
  - netcdf4
  - pip:
    - tensorflow==2.3
    - dask[complete]
    - notebook==6.2.0
    - jupyterlab==2.2.9
    - datatable
    - mimesis
    
